# Generated by Django 3.2.16 on 2022-12-29 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('bank_ac_number', models.PositiveIntegerField(default=0)),
                ('paypal_number', models.PositiveIntegerField(default=0)),
                ('ifsc_code', models.CharField(max_length=50)),
            ],
        ),
    ]
