# Generated by Django 3.2.16 on 2022-12-29 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('result', models.CharField(max_length=50)),
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('timeout', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
